server:
  port: 8002

spring:
  # 设置模式
  profiles:
    active: dev
  application:
    name: Organizepapers

  # 数据源
  # 这是通过jdbc连接器连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/organizepapers?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: productSystem
    # druid 连接池的配置
    druid:
      # 初始化连接大小
      initial-size: 5
      #最大连接池数量
      max-active: 20
      # 最小连接池数量
      min-idle: 3
      # 配置获取连接等待超时的时间 单位毫秒
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000

# Mybatis配置
mybatis:
  # 扫描mapper.xml
  mapper-locations: classpath:mapper/*Mapper.xml
  # pojo类别名
  type-aliases-package: com.papers.domain

# 日志输出mybatis的sql输出
logging:
  level:
    com:
      papers:
        mapper: debug
